### ISSUE TITLE
好像导航栏的下拉列表在中文状态下显示效果不好

### ISSUE THREAD

**Issue by qiansen1386** [vuejs/cn.vuejs.org#104]
![image](https://cloud.githubusercontent.com/assets/1759658/14662374/0c2c8c14-06e8-11e6-9b75-d0326451808b.png)

修改后：

![image](https://cloud.githubusercontent.com/assets/1759658/14662400/44f8d002-06e8-11e6-887b-f2d2d3a8f7ed.png)

主要改动：
```CSS
#nav li {
    display: inline-block;
    position: relative;
    margin: 0 0.6em;
+    min-width: 3em; /* 改善拥挤 */
}

+li.nav-dropdown-container {
+    width: 5em; /* 修复聊天室显示不全 */
+}

#nav .nav-dropdown {
    /* display: none; */
    position: absolute;
    top: 100%;
-     left: 0;
+    left: -30%; /* 改善贴边 */
    background-color: #fff;
    padding: 10px 0;
    border: 1px solid #ddd;
    border-bottom-color: #ccc;
    text-align: left;
    border-radius: 4px;
}
```

请问如何 PR? 咱们的样式表是用的 stylus 么？

我的想法是，有没有啥办法，可以把中文站定制的内容与主站样式表分开？这样每次从主站 merge 会比较方便吧（如果需要 merge 的话）。

亲们，觉得呢？
